export const products = [
  {
    id: 'JK-BOM-BLK-001',
    image: '/src/assets/images/black-bomber-jacket.png',
    name: 'Cropped Tech Bomber – Black',
    description:
      'Turn heads with the Cropped Tech Bomber in black. Sleek and stylish, it’s the perfect blend of streetwear edge and everyday comfort.',
    rating: 5,
    category: 'streetwear',
    type: 'jacket',
    size: ['X-Small', 'Small', 'Medium', 'Large'],
    color: 'black',
    priceCents: 11000,
  },
  {
    id: 'SW-SFT-BLU-041',
    image: '/src/assets/images/blue-sweatshirt.png',
    name: 'Vintage Sweatshirt – Blue',
    description:
      'Stay cozy in the Vintage Sweatshirt. The classic blue tone adds a laid-back feel to your casual lineup.',
    rating: 5,
    category: 'casual',
    type: 'outerwear',
    size: ['Small', 'Medium', 'Large'],
    color: 'blue',
    priceCents: 13000,
  },
  {
    id: 'KN-CDGN-TEL-011',
    image: '/src/assets/images/teal-cardigan.png',
    name: 'Soft Knit Cardigan – Teal',
    description:
      'Wrap yourself in comfort with the Soft Knit Cardigan in teal. A relaxed piece that brings warmth and versatility to any look.',
    rating: 5,
    category: 'modern',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'green',
    priceCents: 7000,
  },
  {
    id: 'PT-DNM-LGT-028',
    image: '/src/assets/images/vintage-denim.png',
    name: 'Loose Fit Denim – Light',
    description:
      'Relaxed and roomy, this light-wash denim brings effortless vintage style to everyday outfits.',
    rating: 5,
    category: 'casual',
    type: 'pants',
    size: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large'],
    color: 'blue',
    priceCents: 8200,
  },
  {
    id: 'SH-SWTS-GRY-031',
    image: '/src/assets/images/grey-sweatshorts.png',
    name: 'Relaxed Sweat Shorts – Grey',
    description:
      'Kick back in comfort with these relaxed sweat shorts. Soft grey tones make them easy to pair with anything.',
    rating: 5,
    category: 'streetwear',
    type: 'shorts',
    size: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large'],
    color: 'grey',
    priceCents: 6500,
  },
  {
    id: 'PO-MIN-BLK-039',
    image: '/src/assets/images/black-polo.png',
    name: 'Boxy Polo Shirt – Black',
    description:
      'Minimal and bold, the Boxy Polo in black brings structured ease to any casual outfit.',
    rating: 5,
    category: 'modern',
    type: 'shirts',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'black',
    priceCents: 4200,
  },
  {
    id: 'TS-CLS-BGE-007',
    image: '/src/assets/images/beige-shirt.png',
    name: 'Everyday Shirt – Beige',
    description:
      'Simple, clean, and reliable. This beige shirt is made for effortless everyday wear.',
    rating: 4,
    category: 'casual',
    type: 'shirts',
    size: ['X-Small', 'Small', 'Medium', 'Large'],
    color: 'beige',
    priceCents: 4200,
  },
  {
    id: 'JK-VARS-NVY-004',
    image: '/src/assets/images/varsity-jacket.png',
    name: 'Varsity Wool – Navy',
    description: 'Classic varsity style with a wool blend. The deep navy shade adds timeless cool.',
    rating: 4,
    category: 'streetwear',
    type: 'jacket',
    size: ['Medium', 'Large', 'X-large'],
    color: 'blue',
    priceCents: 12500,
  },
  {
    id: 'TS-SPT-RED-010',
    image: '/src/assets/images/football-jersey.png',
    name: 'Retro Mesh Football Jersey – Red',
    description:
      'Bring sporty vibes to your day with this breathable retro mesh football jersey in bold red.',
    rating: 5,
    category: 'streetwear',
    type: 'shirts',
    size: ['Small', 'Medium', 'Large'],
    color: 'red',
    priceCents: 9000,
  },
  {
    id: 'KN-VINT-MUL-016',
    image: '/src/assets/images/vintage-knit-sweater.png',
    name: 'Vintage Knit Sweater – Multi',
    description:
      'Cozy up in this multicolor knit sweater that combines warmth with a throwback twist.',
    rating: 5,
    category: 'casual',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'grey',
    priceCents: 11000,
  },
  {
    id: 'PT-SWTP-GRY-022',
    image: '/src/assets/images/grey-sweatpants.png',
    name: 'Classic Sweatpants – Grey',
    description:
      'Soft and casual, these grey sweatpants are your go-to for weekends and relaxed days.',
    rating: 5,
    category: 'streetwear',
    type: 'pants',
    size: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large'],
    color: 'grey',
    priceCents: 7000,
  },
  {
    id: 'SH-DNMS-LGT-032',
    image: '/src/assets/images/light-denim-shorts.png',
    name: 'Denim Shorts – Light Wash',
    description:
      'Laid-back and classic. These faded denim shorts are perfect for warm days and cool looks.',
    rating: 5,
    category: 'casual',
    type: 'shorts',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'blue',
    priceCents: 4800,
  },
  {
    id: 'PO-RES-BGE-035',
    image: '/src/assets/images/beige-polo.png',
    name: 'Resort Collar Polo – Beige',
    description: 'Effortless style meets vacation-ready comfort in this resort collar polo.',
    rating: 4,
    category: 'casual',
    type: 'shirts',
    size: ['X-Small', 'Small', 'Medium', 'Large'],
    color: 'beige',
    priceCents: 4600,
  },
  {
    id: 'SW-HOOD-GRY-042',
    image: '/src/assets/images/grey-hoodie.png',
    name: 'Essential Zip Hoodie – Grey',
    description:
      'A layering staple, the Essential Zip Hoodie keeps you warm without weighing you down.',
    rating: 4,
    category: 'streetwear',
    type: 'outerwear',
    size: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large'],
    color: 'grey',
    priceCents: 4600,
  },
  {
    id: 'JK-LTHR-BLK-005',
    image: '/src/assets/images/leather-jacket.png',
    name: 'Classic Leather Jacket – Black',
    description:
      'Nothing beats the edge of a classic leather jacket. Black, bold, and built to last.',
    rating: 4,
    category: 'streetwear',
    type: 'jacket',
    size: ['Medium', 'Large', 'X-large'],
    color: 'black',
    priceCents: 18500,
  },
  {
    id: 'KN-VEST-OLV-015',
    image: '/src/assets/images/olive-knit-vest.png',
    name: 'Classic Knit Vest – Olive',
    description:
      'Layer smart with the Classic Knit Vest. Olive green brings just the right contrast.',
    rating: 4,
    category: 'formal',
    type: 'knitted',
    size: ['X-Small', 'Small', 'Medium', 'Large'],
    color: 'green',
    priceCents: 6000,
  },
  {
    id: 'PT-DNM-GRY-029',
    image: '/src/assets/images/grey-denim.png',
    name: 'Classic Vintage Denim – Grey',
    description: 'A vintage cut with a modern grey tone. These jeans are made to move with you.',
    rating: 5,
    category: 'modern',
    type: 'pants',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'grey',
    priceCents: 9000,
  },
  {
    id: 'SH-CHNS-BGE-034',
    image: '/src/assets/images/beige-chino-shorts.png',
    name: 'Soft Chino Shorts – Beige',
    description:
      'A refined short for casual days. These beige chinos are soft, light, and breathable.',
    rating: 4,
    category: 'casual',
    type: 'shorts',
    size: ['Small', 'Medium', 'Large'],
    color: 'beige',
    priceCents: 4500,
  },
  {
    id: 'KN-CDGN-BGE-013',
    image: '/src/assets/images/beige-cardigan.png',
    name: 'Essential Cardigan – Beige',
    description:
      'Lightweight layering made easy. The Essential Cardigan in beige is versatile for any season.',
    rating: 5,
    category: 'modern',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'beige',
    priceCents: 6800,
  },
  {
    id: 'PO-BOX-PUR-037',
    image: '/src/assets/images/purple-polo.png',
    name: 'Oversized Polo Shirt – Purple',
    description:
      'Statement-making comfort in a bold purple tone. This oversized polo adds flair to any casual outfit.',
    rating: 4,
    category: 'streetwear',
    type: 'shirts',
    size: ['Small', 'Medium', 'Large'],
    color: 'purple',
    priceCents: 4800,
  },
  {
    id: 'KN-COOG-MIX-017',
    image: '/src/assets/images/coogi-knit-sweater.png',
    name: 'Coogi-Style Knit Sweater',
    description:
      'Colorful, bold, and undeniably cozy. This knit sweater brings retro energy to cooler days.',
    rating: 5,
    category: 'streetwear',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'black',
    priceCents: 11000,
  },
  {
    id: 'PT-TRSR-BGE-018',
    image: '/src/assets/images/beige-trouser.png',
    name: 'Tapered Trousers – Beige',
    description:
      'Smart tailoring meets casual ease. These tapered beige trousers refine your everyday rotation.',
    rating: 4,
    category: 'formal',
    type: 'pants',
    size: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large'],
    color: 'beige',
    priceCents: 6500,
  },
  {
    id: 'KN-VEST-RED-014',
    image: '/src/assets/images/red-knit-vest.png',
    name: 'Textured Knit Vest – Red',
    description:
      'Stand out with the bold color and rich texture of this red knit vest—ideal for layering.',
    rating: 4,
    category: 'formal',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large'],
    color: 'red',
    priceCents: 5800,
  },
  {
    id: 'SW-HVY-BGE-040',
    image: '/src/assets/images/beige-sweatshirt.png',
    name: 'Heavyweight Sweatshirt – Beige',
    description:
      'Thicker and warmer than your average crewneck. This heavyweight sweatshirt brings lasting comfort.',
    rating: 5,
    category: 'modern',
    type: 'outerwear',
    size: ['Medium', 'Large', 'X-large'],
    color: 'beige',
    priceCents: 6000,
  },
  {
    id: 'TS-CLS-PUR-006',
    image: '/src/assets/images/purple-shirt.png',
    name: 'Drop Shoulder Shirt – Purple',
    description:
      'A relaxed silhouette in a striking shade. This drop shoulder shirt redefines casual boldness.',
    rating: 4,
    category: 'modern',
    type: 'shirts',
    size: ['Small', 'Medium', 'Large'],
    color: 'purple',
    priceCents: 4500,
  },
];

export const newArrival = [
  {
    id: 'JK-VARS-NVY-004',
    image: '/src/assets/images/varsity-jacket.png',
    name: 'Varsity Wool – Navy',
    rating: 4,
    category: 'streetwear',
    type: 'jacket',
    size: ['Medium', 'Large', 'X-large'],
    color: 'blue',
    priceCents: 12500,
  },
  {
    id: 'PO-MIN-BLK-039',
    image: '/src/assets/images/black-polo.png',
    name: 'Boxy Polo Shirt – Black',
    rating: 5,
    category: 'modern',
    type: 'shirts',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'black',
    priceCents: 4200,
  },
  {
    id: 'SH-DNMS-LGT-032',
    image: '/src/assets/images/light-denim-shorts.png',
    name: 'Denim Shorts – Light Wash',
    rating: 5,
    category: 'casual',
    type: 'shorts',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'blue',
    priceCents: 4800,
  },
  {
    id: 'KN-COOG-MIX-017',
    image: '/src/assets/images/coogi-knit-sweater.png',
    name: 'Coogi-Style Knit Sweater',
    rating: 5,
    category: 'streetwear',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'black',
    priceCents: 110000,
  },
];

export const topSelling = [
  {
    id: 'TS-SPT-RED-010',
    image: '/src/assets/images/football-jersey.png',
    name: 'Retro Mesh Football Jersey – Red',
    rating: 5,
    category: 'streetwear',
    type: 'shirts',
    size: ['Small', 'Medium', 'Large'],
    color: 'red',
    priceCents: 9000,
  },
  {
    id: 'SW-SFT-BLU-041',
    image: '/src/assets/images/blue-sweatshirt.png',
    name: 'Vintage Sweatshirt – Blue',
    rating: 5,
    category: 'casual',
    type: 'outerwear',
    size: ['Small', 'Medium', 'Large'],
    color: 'blue',
    priceCents: 13000,
  },
  {
    id: 'KN-CDGN-BGE-013',
    image: '/src/assets/images/beige-cardigan.png',
    name: 'Essential Cardigan – Beige',
    rating: 5,
    category: 'modern',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'beige',
    priceCents: 6800,
  },
  {
    id: 'KN-VINT-MUL-016',
    image: '/src/assets/images/vintage-knit-sweater.png',
    name: 'Vintage Knit Sweater – Multi',
    rating: 5,
    category: 'casual',
    type: 'knitted',
    size: ['Small', 'Medium', 'Large', 'X-large'],
    color: 'grey',
    priceCents: 11000,
  },
];
